lint/main.go

[lint] Add silent and color flags

---

languageserver/go.mod
languageserver/go.sum
languageserver/integration/flow.go

Update the usage of the new Flowkit API.
______

[LS] Flowkit API update

---

languageserver/server/server.go
languageserver/server/stdlib.go
languageserver/test/index.test.ts

Closes #21 #62
Adding the augmented config for the checker in case of script checking.
______

[LS] Augmented checker configuration for scripts

---

languageserver/server/server.go
languageserver/server/stdlib.go

References #63 
Refactor based on the comments in PR #63
______

[LS] Refactor creation of config

---

languageserver/integration/flow.go
languageserver/integration/integration.go
languageserver/integration/mock_flow_test.go
languageserver/integration/resolvers.go
languageserver/server/server.go

Closes #65 
Implements resolving of account access checker.
______

[LS] Implement account access check

---

languageserver/go.mod
languageserver/go.sum
languageserver/integration/flow.go
languageserver/integration/mock_flow_test.go

Update flowkit API change for adding contracts.
______

[LS] Update add contract API change

---

languageserver/integration/flow.go
languageserver/integration/integration.go
languageserver/integration/mock_flow_test.go
languageserver/integration/resolvers.go
languageserver/integration/resolvers_test.go
languageserver/server/location.go
languageserver/test/index.test.ts

Putting back some code that was deleted by mistake. We still need to have resolvers for string 🤦 
______

[LS] String import resolver

---

languageserver/integration/resolvers.go

Improved path clean for windows

[LS] fix path clean on windows

---

languageserver/go.mod
languageserver/go.sum

upgrade sentry dependency version
______

update version of sentry dependency

---

languageserver/server/server.go

Closes https://github.com/onflow/cadence-tools/issues/98
This was originally described in https://github.com/orgs/onflow/discussions/1330
**Before:**
**After:**
______

[LS] Fix import failure of `Test` contract

---

languageserver/integration/commands_test.go
languageserver/server/server.go

Enable attachments and account linking

---

languageserver/server/server.go

Turn capability controllers on.
______

Enable capability controllers

---

languageserver/test/index.test.ts

Add tests for:
- Account linking
- Attachments
- Capability Controllers
______

[LS] Add test for Cadence features behind feature flags

---

test/test_framework_test.go

Also made some stylistic changes where indentation was mixed with tabs and spaces.
______

[test] Update test scripts with the latest API additions

---

languageserver/README.md

This PR updates the LS docs to update the release process instructions.
______

[LS] Update release process

---

npm-packages/cadence-language-server/README.md

Update release instructions for LS
______

[NPM] Release instructions for LS

---

.github/workflows/ci.yml

Improve CI: Only run job for project if files changed

---

test/test_framework_test.go

Closes https://github.com/onflow/cadence-tools/issues/261
Add some assertions to verify the proper functionality of the `RandomBeaconHistory` built-in contract.
______

[test] Add some test assertions for `RandomBeaconHistory`'s usage

---

test/emulator_backend.go
test/test_framework_provider.go
test/test_framework_test.go
test/test_runner.go

Port of https://github.com/onflow/cadence-tools/pull/267
______

[Test] Merge pull request #267 from onflow/jribbink/add-logger (test/v0.14)

---

lint/go.mod
lint/go.sum

- [onflow/flow-go-sdk v1.0.0-M7](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M7)

[lint] Update to SDK v1.0.0-M7

---

test/emulator_backend.go
test/test_framework_test.go
test/test_runner.go

Adds support for the newly-introduced `Burner` system contract.
______

[test] Add `Burner` system contract

---

.github/workflows/ci.yml
languageserver/Makefile
npm-packages/cadence-language-server/jest.config.js
npm-packages/cadence-language-server/package.json
npm-packages/cadence-language-server/src/go.js
npm-packages/cadence-language-server/tests/index.test.ts

Closes #243 
Restores the WASM build using the new build tag from `onflow/crypto`
______

[LS] Restore WASM build

---

languageserver/go.mod
languageserver/go.sum

[LS] Update flowkit to alpha 19
