onflow/cadence-tools

test/emulator_backend.go, test/go.mod, test/go.sum, test/test_framework_test.go, test/test_runner.go
Closes #33
Use the same interpreter instance which is used to run the test-script also to decode values, rather than instantiating a new interpreter instance. 
Depends on: https://github.com/onflow/cadence/pull/2074
______
=> Fix value decoding during argument passing and return value decoding

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Closes #?? (didn't create an issue for it)
This repo was missing the issue templates. The duplicated template directly under the .github folder was needed for github properly auto filling issues when you create a new one. 
______
=> Include issue templates

languageserver/integration/flow.go
Closes: #49 
This PR is implementing usage of a local emulator if one is already running, otherwise, it hosts it's own. The reason for this is to allow developer share same emulator between tools. 
______
=> [LS] Using local emulator

languageserver/integration/commands.go
Closes #55
This handles windows paths with prefix `/` otherwise the location is not valid. 
Related to https://github.com/microsoft/vscode/issues/170618
______
=> [LS] Strip extra slash on windows paths

languageserver/integration/commands.go, languageserver/integration/flow.go, languageserver/integration/integration.go, languageserver/integration/mock_flow_test.go, languageserver/integration/resolvers.go
Closes https://github.com/onflow/vscode-cadence/issues/224
Clean windows paths in import resolvers since they are passed with a prefix and URL encoded format (e.g. `/c%3A/foo/bar.cdc`)
______
=> [LS] Bugfix clean Windows paths in resolvers

languageserver/cmd/languageserver/main.go, languageserver/go.mod, languageserver/run.sh, languageserver/test/index.test.ts
Make the flow client flag consistent with CLI and also change the run.sh script so it actually passes the flags to the ls.
______
=> [LS] Flow client flag consistent with CLI

languageserver/server/server.go
LS shouldn't decide on what is important to the client. Log the shutdown message instead.
______
=> [LS] Don't force showing messages

languageserver/integration/mock_flow_test.go
Forgot to regenerate mocks. Should be changed in the future to not require this in the first place.
=> [LS] Mock regenreation

lint/analyzer.go, lint/cmd/lint/main.go, lint/deprecated_key_functions_analyzer.go, lint/number_function_argument_analyzer.go, lint/redundant_cast_analyzer.go, lint/reference_operator_analyzer.go, lint/unnecessary_force_analyzer.go
Similar to golangci-lint, allow linters/analyzers to be loaded at run-time using Go's plugin system.
______
=> Lint: Add support for plugins

test/test_framework_test.go, test/test_runner.go
Work towards https://github.com/onflow/developer-grants/issues/132
**Complementary PRs:**
- https://github.com/onflow/flow-cli/pull/827
- https://github.com/onflow/cadence/pull/2296
- Enable coverage reporting for test runners
- Include also the test script name, when printing test results for each script.
______
=> Enable coverage reporting for test runners

lint/auth_account_parameter_analyzer.go, lint/auth_account_parameter_analyzer_test.go
Closes https://github.com/onflow/cadence-tools/issues/4
It is an anti-pattern to pass `AuthAccount`s to functions.
We introduce a new analyzer to detect and report parameters that have an `AuthAccount` type.
______
=> Add analyzer to detect and report parameters that have an `AuthAccount` type

languageserver/README.md
Fixes a few links to point to the correct directory path in the README.
______
=> Fix links to the packages in the README

test/emulator_backend.go, test/test_runner.go
Closes https://github.com/onflow/cadence-tools/issues/103
Displays Cadence logs from unit/integration tests and test files, to the console.
**Note**: This is currently the default behavior, without a flag to enable/disable it.
**Note 2**: I tried to make the logs have the same look & feel, because some come from the Emulator's `Blockchain` ([CadenceHook](https://github.com/onflow/flow-emulator/blob/master/blockchain.go#L535)), however that ends up in double printing the rest of the logs, e.g:
______
=> Display Cadence logs during testing

test/emulator_backend.go, test/test_framework_test.go
Work towards: https://github.com/onflow/developer-grants/issues/132
Certain smart contracts, which are essential for the functioning of the Flow blockchain, are not needed in the context of coverage reporting. We exclude them, in order to avoid skewing the coverage report metrics.
______
=> Exclude the omnipresent locations from code coverage

languageserver/server/server.go
When providing an inlay hint for a resource-kinded type, also provide the type annotation (`@`).
Noticed this during the Office Hours :-) 
______
=> Fix inlay hints: add type annotation for resource types

test/emulator_backend.go, test/test_framework_test.go, test/test_runner.go
Work towards: https://github.com/onflow/developer-grants/issues/148
The general idea here, is to have better control at resetting the state of the blockchain, and some flexible hooks to run before/after each test case. For example:
```cadence
import Test
pub fun beforeEach() {
// Reset the state of the blockchain
blockchain.reset()
}
// or the afterEach() can be used to reset the state
pub fun afterEach() {
blockchain.reset()
}
```
This feature was first discussed about in https://github.com/orgs/onflow/discussions/1330
______
=> Add `EmulatorBackend.Reset` method and `beforeEach` / `afterEach` hooks

languageserver/conversion/conversion.go, languageserver/server/server.go
Closes #125 
This PR solves import symbols having no name in LSP responses and causing errors in the client/vscode extension.
______
=> Fix unnamed import symbols

test/emulator_backend.go, test/go.mod, test/test_framework_test.go, test/test_runner.go
Work towards: https://github.com/onflow/developer-grants/issues/148
Companion PR: https://github.com/onflow/cadence/pull/2505 :heavy_check_mark: 
Provides a way to retrieve logs from the `Blockchain`, programmatically, from the testing framework, with:
```cadence
import Test
blockchain.logs()
```
Also improves the look & feel for logs that come from test files. E.g:
______
=> Retrieve `Blockchain` logs

lint/auth_account_parameter_analyzer.go, lint/auth_account_parameter_analyzer_test.go
Fix a nil-dereference when analyzing function declarations that should be ignored.
______
=> Fix AuthAccount analyzer

lint/go.mod, lint/go.sum
- [onflow/cadence v0.39.4](https://github.com/onflow/cadence/releases/tag/v0.39.4)
- [onflow/flow-go-sdk v0.41.2](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.2)
=> [lint] Update to Cadence v0.39.4

test/emulator_backend.go, test/test_framework_test.go, test/test_runner.go
- Fix regex issue, when parsing non-string log messages
- Add support for `stdlib` events that have type `flow.*`
- Allow importing the `Test` contract in helper files
-  Update `EmulatorBackend.Reset()` function to use `Blockchain.RollbackToBlockHeight()` instead of `Blockchain.ReloadBlockchain()`
- Improve `CoverageReport` metrics to include only contracts
Such events, can even be printed to the console:
```bash
1:04PM DBG LOG: flow.AccountCreated(address: 0x01cf0e2f2f715450)
```
______
=> Add support for retrieving `stdlib` events

languageserver/go.mod, languageserver/go.sum
References: https://github.com/onflow/cadence-tools/issues/129
use newly released cadence version [v0.39.6](https://github.com/onflow/cadence/releases/tag/v0.39.6)
Should add contracts init to "Entry Points"
______
=> update reference to cadence to use newest version

test/emulator_backend.go, test/test_framework_test.go
The return errors were the following:
```bash
error: assertion failed: internal error: cannot import array: elements do not belong to the same type
```
And
```bash
error: assertion failed: cannot import dictionary: keys does not belong to the same type
```
This was due to the fact that `runtime.ImportValue` would pass `nil` for the `expectedType` parameter
______
=> Fix error when returning empty `Array` & `Dictionary` values from scripts

test/emulator_backend.go, test/test_framework_test.go
- Set log-level to `zerolog.InfoLevel` for logger passed to `emulator.WithServerLogger`
- Make test assertion for event length more resistant to version bumps of Emulator
- Fix regression that was introduced from running `CoverageReport.Reset()`
______
=> Fix verbose logging

lint/go.mod, lint/go.sum
- [onflow/cadence v0.39.12](https://github.com/onflow/cadence/releases/tag/v0.39.12)
- [onflow/flow-go-sdk v0.41.6](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.6)
=> [lint] Update to Cadence v0.39.12

test/emulator_backend.go, test/test_framework_test.go
The new import format was not properly supported. For example:
```cadence
import "FUSD"
import "ExampleNFT"
```
would not work when because both contracts reside on the same address. This would crash with:
```bash
error: panic: [Error Code: 1101] error caused by: 1 error occurred:
* [Error Code: 1101] cadence runtime error: Execution failed:
error: cannot redeclare contract: `ExampleNFT` is already declared
--> efee235c05f52610b48ac1c24e3c3b9bb88fc2bbc84ad7100be68cd7326e9487:0:0
``` 
______
=> [test] Fix import replacement for new import format

languageserver/go.mod, languageserver/go.sum
The auto-update PR https://github.com/onflow/cadence-tools/pull/173 somehow didn't update the lint version in LS.
______
=> [LS] Update to cadence-tools/lint v0.10.1

languageserver/test/index.test.ts
When tests fail, the LS process keeps running an jest never exits.
This causes the CI job to run for 6 hours ... 
e.g. https://github.com/onflow/cadence-tools/actions/runs/5359904438?pr=156
Ensure the LS is always send an exit notification so it shuts down.
______
=> [LS] Ensure LS exit, even if test fails

test/blockchain_helpers.cdc, test/blockchain_helpers.go, test/emulator_backend.go, test/scripts.go, test/scripts/get_current_block_height.cdc, test/scripts/get_flow_balance.cdc, test/test_framework_test.go, test/test_runner.go, test/transactions.go, test/transactions/burn_flow.cdc, test/transactions/mint_flow.cdc
Closes https://github.com/onflow/cadence-tools/issues/171
Adding tests & API changes for the following improvements:
- Expose current block information, such as **block height**
- Expose **balance** for test accounts
- Add helper function to **mint** FLOW to a test account
- Add helper function to **burn** FLOW from a test account
- **Validate test function signature**, no arguments or return values
Sample usage:
```cadence
import Test
import BlockchainHelpers
pub let helpers = BlockchainHelpers(blockchain: blockchain)
pub let account = blockchain.createAccount()
// Retrieve current block height
pub let height = helpers.getCurrentBlockHeight()
// Retrieve the Flow token balance of a test account
pub let balance = …
```
=> [test] Cadence testing framework improvements

languageserver/go.mod, languageserver/go.sum, languageserver/server/server.go
**Depends on:** https://github.com/onflow/cadence-tools/pull/181
The Cadence testing framework has introduced a new identifier location: `BlockchainHelpers`, so we add support for it in the language server. Otherwise the checking would fail.
______
=> [LS] Add checker support for `BlockchainHelpers` identifier location

test/emulator_backend.go, test/go.mod, test/go.sum, test/test_framework_test.go
**Depends on:** https://github.com/onflow/cadence/pull/2696
Adding tests & API changes for the following improvements:
- Allow **rolling back** at a specific block height
- Add helper function to **assert error message** on `ScriptResult`/`TransactionResult`
```cadence
import Test
import BlockchainHelpers
pub let helpers = BlockchainHelpers(blockchain: blockchain)
// Retrieve current block height
pub let height = helpers.getCurrentBlockHeight()
// Reset (rollback) the blockchain to a given block height
blockchain.reset(height)
pub let script = Test.readFile("../scripts/get_integer_traits.cdc")
pub let result = blockchain.executeScript(script, [])
// Assert that a script/transaction errored and the error message contains a specified …
```
=> [test] Update emulator backend interface

test/test_framework_test.go
Context: https://github.com/onflow/cadence-tools/issues/172
Related PR: https://github.com/onflow/cadence/pull/2717
Adds some assertions to verify that loading of standard library flow events works as expected.
______
=> [test] Add assertions to verify loading of standard library flow events

lint/go.mod, lint/go.sum
Update to
- cadence [v0.41.0-stable-cadence.1](https://github.com/onflow/cadence/releases/tag/v0.41.0-stable-cadence.1)
- flow-go-sdk [v0.44.0-stable-cadence.1](https://github.com/onflow/flow-go-sdk/releases/tag/v0.44.0-stable-cadence.1)
______
=> [lint] Update cadence version to v0.41.0-stable-cadence.1

test/emulator_backend.go, test/go.mod, test/go.sum, test/test_framework_test.go
**Depends on:** https://github.com/onflow/cadence/pull/2734
Implements the `TestFramework.MoveTime(int64)`, so that users can manipulate the blockchain's time.
It passes a custom `Clock` implementation to the `EmulatorBackend`.
Example usage:
```cadence
import Test
pub fun test() {
let blockchain = Test.newEmulatorBlockchain()
// timeDelta is the representation of 35 days,
// in the form of seconds.
let timeDelta = Fix64(35 * 24 * 60 * 60)
blockchain.moveTime(by: timeDelta)
// A negative time delta moves the time backwards
blockchain.moveTime(by: timeDelta * -1.0)
}
```
______
=> [test] Allow setting blockchain's clock

test/test_framework_test.go, test/test_runner.go
Users can inject a random seed, in order for test cases to be executed randomly. This can help uncover flaky tests and possibly bugs in source code. Given the same random seed, the sequence of test case execution should be the same. This is so that users can debug the cause of flakiness.
______
=> [test] Allow `TestRunner` to execute test cases randomly

test/emulator_backend.go, test/go.mod, test/go.sum, test/test_framework_provider.go, test/test_framework_test.go, test/test_runner.go
Continuation of https://github.com/onflow/cadence-tools/issues/139
Move parts of `EmulatorBackend` to `TestFrameworkProvider`.
`EmulatorBackend` now implements `stdlib.Blockchain`, while `TestFrameworkProvider` implements `stdlib.TestFramework`.
This separation allows us to create multiple `EmulatorBackend` instances, with `Test.newEmulatorBlockchain()`, that come with clean state.
______
=> [test] Clean state for each emulator backend instance

test/emulator_backend.go, test/go.mod, test/go.sum, test/test_framework_test.go
**Depends on:** https://github.com/onflow/cadence-tools/pull/205
Allow developers to create snapshots of the blockchain's current ledge state, and load them on demand at any time. For example:
```cadence
import Test
import BlockchainHelpers
pub let helpers = BlockchainHelpers(blockchain: blockchain)
pub fun test() {
let admin = blockchain.createAccount()
blockchain.createSnapshot("adminCreated")
helpers.mintFlow(to: admin, amount: 1000.0)
blockchain.createSnapshot("adminFunded")
var balance = helpers.getFlowBalance(for: admin)
Test.assertEqual(1000.0, balance)
blockchain.loadSnapshot("adminCreated")
balance = helpers.getFlowBalance(for: admin)
Test.assertEqual(0.0, balance)
blockchain.loadSnapshot("adminFunded")
balance = …
```
=> [test] Add blockchain snapshots

test/emulator_backend.go, test/test_framework_test.go, test/test_runner.go
Below is a working example of utilizing types from deployed contracts, inside of a test script:
```cadence
import Test
// The address `0x0000000000000005` comes from the account created in the lines below.
// This is where the `FooContract` is also deployed in the `setup()` function.
// However, we can't avoid the chicken-and-egg problem, developers will have to probably
// log the account to get the address, which will be sequential and guaranteed to be the same.
// import FooContract from account.address is not possible.
import FooContract from 0x0000000000000005
pub let account = blockchain.createAccount()
pub fun setup() {
let contractCode = Test.readFile("../contracts/FooContract.cdc")
let err = blockchain.deployContract(
name: …
```
=> [test] Allow test scripts to import types from deployed contracts

.github/workflows/ci.yml, Makefile
Run CI separately for each sub-module, so that test-failures can be analyzed separately. Also avoid skipping modules if there were test failure in one module.
______
=> Run CI separately for each sub-module

languageserver/server/stdlib.go
Proactive addition for the breaking change introduced in https://github.com/onflow/cadence/commit/b1ca6faf65a18ffc3cbf3596a3ef6118d7720663
______
=> [LS] Implement `ReadRandom` for standardLibrary type

test/go.mod, test/go.sum
- [onflow/flow-emulator v0.56.0](https://github.com/onflow/flow-emulator/releases/tag/v0.56.0)
=> Auto update to onflow/flow-emulator v0.56.0

lint/go.mod, lint/go.sum
- [onflow/cadence v0.42.1](https://github.com/onflow/cadence/releases/tag/v0.42.1)
- [onflow/flow-go-sdk v0.41.12](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.12)
=> [lint] Update to Cadence v0.42.1

languageserver/cmd/languageserver/main_wasm.go
closes #168 
Adds StringImportResolver support to WASM LS.  Needed for new import syntax.
______
=> [LS] Add string import resolver to WASM LS

test/emulator_backend.go
After some feedback from community members using the testing framework for their dApps, the number of 10 predefined accounts for contract deployments is rather low. To better simulate the setup of `testnet`/`mainnet`, each contract should be deployed in its own account. To test for fields/methods with access modifier `access(account)`.
______
=> [test] Increase the number of predefined accounts to 20

lint/go.mod, lint/go.sum
- [onflow/cadence v0.42.5](https://github.com/onflow/cadence/releases/tag/v0.42.5)
- [onflow/flow-go-sdk v0.41.16](https://github.com/onflow/flow-go-sdk/releases/tag/v0.41.16)
=> [lint] Update to Cadence v0.42.5

languageserver/cmd/languageserver/main_wasm.go, languageserver/go.mod, languageserver/go.sum, languageserver/server/server.go
=> [LS] Fix wasm target

test/helpers/blockchain_helpers.go, test/helpers/blockchain_helpers_test.go, test/test_framework_test.go, test/test_runner.go
- Minor improvements regarding the `helpers` package
- Fix bug regarding import of built-in `Crypto` contract in other contracts, besides the test file itself
- Simplify the `CheckerConfig.ImportHandler` on `TestRunner.parseAndCheckImport`. This fixes a bug when importing nested contracts, e.g. `A` imports `B` imports `C`.
______
=> [test] Test framework bug fixes

test/go.mod, test/test_framework_test.go, test/test_runner.go
Work towards https://github.com/onflow/developer-grants/issues/216
In `InterpreterConfig.ContractValueHandler` function, we would override the interpreter's shared state with a new storage based on emulator's ledger.
```go
storage := runtime.NewStorage(
r.backend.blockchain.NewScriptEnvironment(),
nil,
)
// Update the storage to reflect the changes
// from deployments in setup() function.
inter.SharedState.Config.Storage = storage
```
This proved to be problematic, as the new storage would not contain the constructed composite values needed for testing, e.g. `I.Test`. Resulting in the following error:
```shell
error: internal error: slab (0x0.7) not found: slab not found for stored value
```
The `slab (0x0.7)` would contain the emulator backend:
```cadence
access(all) contract Test {
/// …
```
=> [test] Fix storage errors for unit testing

test/emulator_backend.go, test/test_framework_provider.go, test/test_framework_test.go, test/test_runner.go
Closes #269 
Adds a `WithLogger` option to the test runner and defaults to suppressed logs if none is provided (could also output to stdio if preferred, but emulator uses the suppress-if-not-provided pattern already so it felt intuitive to follow this).
I noticed that `master` is now on stable-cadence -- not exactly sure which branch I should be targeting to get these changes into pre-cadence-1.0 release (cc @turbolent)
______
=> [Test] Add WithLogger to TestRunner and default to zerolog.Nop()

test/test_framework_test.go, test/test_runner.go
Closes https://github.com/onflow/cadence-tools/issues/254
When printing the test results, it is difficult to guess from which test file the failures come from, e.g.
```shell
error: panic: runtime error
--> 7465737400000000000000000000000000000000000000000000000000000000:9:12
```
vs
```shell
error: panic: runtime error
--> tests/test_script.cdc:9:12
```
______
=> [test] Use filenames instead of script ID when printing test results

docgen/README.md
Path under How To Run section is refering the old struct where the doc-gen tool was under the general cadence repo
______
=> [DG] Fix how to run path

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-M6](https://github.com/onflow/cadence/releases/tag/v1.0.0-M6)
- [onflow/flow-go-sdk v1.0.0-M3](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M3)
=> [lint] Update to Cadence v1.0.0-M6

test/go.mod, test/go.sum, test/test_framework_test.go
- [onflow/cadence v1.0.0-M7](https://github.com/onflow/cadence/releases/tag/v1.0.0-M7)
- [onflow/flow-go-sdk v1.0.0-M4](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M4)
- [onflow/flow-go 6b0ce48](https://github.com/onflow/flow-go/commit/6b0ce48)
- [onflow/flow-emulator v1.0.0-M6](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-M6)
=> [test] Update to flow-go 6b0ce48

lint/cadence_v1_analyzer.go, lint/cadence_v1_analyzer_test.go
Adds missing checks for nil pointer dereferences when traversing type annotations.
Ran into this issue in CI for https://github.com/onflow/cadence-tools/pull/286
______
=> [lint] Check for nil pointers in CadenceV1Analyzer type annotation inspection

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-M8](https://github.com/onflow/cadence/releases/tag/v1.0.0-M8)
- [onflow/flow-go-sdk v1.0.0-M5](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M5)
=> [lint] Update to Cadence v1.0.0-M8

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-M9](https://github.com/onflow/cadence/releases/tag/v1.0.0-M9)
- [onflow/flow-go-sdk v1.0.0-M8](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-M8)
=> [lint] Update to Cadence v1.0.0-M9

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.12](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.12)
- [onflow/flow-go-sdk v1.0.0-preview.10](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.10)
=> [lint] Update to Cadence v1.0.0-preview.12

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.13](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.13)
- [onflow/flow-go-sdk v1.0.0-preview.11](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.11)
=> [lint] Update to Cadence v1.0.0-preview.13

lint/cadence_v1_analyzer.go, lint/cadence_v1_analyzer_test.go
Closes #314 
Adding this was an oversight and ends up causing more harm than the value it provides.  IMO we should instead rely on clients to add this information if they need it (based on the category), and adding this only pollutes the diagnostic message.
I'll make a PR to add this messaging to the language server after this is merged
______
=> [lint] Remove `[Cadence 1.0]` from Cadence V1 Diagnostics

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.15](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.15)
- [onflow/flow-go-sdk v1.0.0-preview.13](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.13)
=> [lint] Update to Cadence v1.0.0-preview.15

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.16](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.16)
- [onflow/flow-go-sdk v1.0.0-preview.14](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.14)
=> [lint] Update to Cadence v1.0.0-preview.16

test/emulator_backend.go, test/test_framework_test.go
As requested from the community, it can be useful sometimes to be able to deploy contracts to the service account.
______
=> [test] Allow contract deployments to service account

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.18](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.18)
- [onflow/flow-go-sdk v1.0.0-preview.16](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.16)
=> [lint] Update to Cadence v1.0.0-preview.18

test/test_framework_test.go, test/test_runner.go
Allow importing the `EVM` contract in test scripts, so that developers can reference the types defined in this contract.
______
=> [test] Properly setup EVM environment to allow usage of EVM types in test scripts

languageserver/Makefile, npm-packages/cadence-language-server/package.json
related to #345 
Since `onflow/crypto` has been updated to v0.25.1, we can restore the WASM build.
______
=> [LS] Restore WASM build on v0.33 branch

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.25](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.25)
- [onflow/flow-go-sdk v1.0.0-preview.25](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.25)
=> [lint] Update to Cadence v1.0.0-preview.25

languageserver/go.mod, languageserver/go.sum
=> [LS] Update flowkit to 1.18.0

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.29](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.29)
- [onflow/flow-go-sdk v1.0.0-preview.30](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.30)
=> [lint] Update to Cadence v1.0.0-preview.29

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.32](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.32)
- [onflow/flow-go-sdk v1.0.0-preview.34](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.34)
=> [lint] Update to Cadence v1.0.0-preview.32

test/go.mod, test/go.sum, test/test_runner.go
- [onflow/cadence v1.0.0-preview.34](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.34)
- [onflow/flow-go-sdk v1.0.0-preview.36](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.36)
- [onflow/flow-go v0.35.14-crescendo-preview.27](https://github.com/onflow/flow-go/releases/tag/v0.35.14-crescendo-preview.27)
- [onflow/flow-emulator v1.0.0-preview.32](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-preview.32)
=> [test] Update to Cadence v1.0.0-preview.34

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.35](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.35)
- [onflow/flow-go-sdk v1.0.0-preview.37](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.37)
=> [lint] Update to Cadence v1.0.0-preview.35

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.37](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.37)
- [onflow/flow-go-sdk v1.0.0-preview.39](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.39)
=> [lint] Update to Cadence v1.0.0-preview.37

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.38](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.38)
- [onflow/flow-go-sdk v1.0.0-preview.41](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.41)
=> [lint] Update to Cadence v1.0.0-preview.38

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.39](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.39)
- [onflow/flow-go-sdk v1.0.0-preview.42](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.42)
=> [lint] Update to Cadence v1.0.0-preview.39

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.42](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.42)
- [onflow/flow-go-sdk v1.0.0-preview.45](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.45)
=> [lint] Update to Cadence v1.0.0-preview.42

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.48](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.48)
- [onflow/flow-go-sdk v1.0.0-preview.50](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.50)
=> [lint] Update to Cadence v1.0.0-preview.48

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.50](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.50)
- [onflow/flow-go-sdk v1.0.0-preview.53](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.53)
=> [lint] Update to Cadence v1.0.0-preview.50

lint/go.mod, lint/go.sum
- [onflow/cadence v1.0.0-preview.51](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.51)
- [onflow/flow-go-sdk v1.0.0-preview.54](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.54)
=> [lint] Update to Cadence v1.0.0-preview.51

languageserver/server/document_test.go, languageserver/server/server.go
`pub`, `priv`, and `pub(set)` got removed in Cadence 1.0, so they should not be proposed anymore. Instead propose `access(all)`
______
=> [LS] Update access modifiers to Cadence 1.0

test/emulator_backend.go, test/go.mod, test/test_framework_test.go, test/test_runner.go
Depends on / work towards #470 
- `AccountV2Migration` was removed from flow-go, as the migration to V2 is complete
- Switch parameters to use the respective context interfaces instead of the interpreter
- Interpreter errors are pointer types now
- `StorageFormatV2Enabled` feature flag was removed, it is now always enabled
This required several changes to Cadence: https://github.com/onflow/cadence/pull/4018
______
=> [Test] Update to Cadence v1.6.0

languageserver/server/server.go
Work towards #467 
When hovering at the end of a member identifier, lookup fails because the column is outside of the identifier. 
Re-attempt occurrence lookup with the preceding position.
______
=> [LS] Improve hover
